# Generated by Django 5.1.5 on 2026-03-06 02:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvapp', '0002_pokerevent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamescore',
            options={'ordering': ['rank', '-score']},
        ),
        migrations.AlterModelOptions(
            name='monthlygame',
            options={'get_latest_by': 'uploaded_at', 'ordering': ['year', 'month']},
        ),
        migrations.AlterModelOptions(
            name='overallstats',
            options={'get_latest_by': 'uploaded_at', 'ordering': ['-year'], 'verbose_name_plural': 'Overall Stats'},
        ),
        migrations.AlterModelOptions(
            name='playeroverallstat',
            options={'ordering': ['-eoy_pool']},
        ),
        migrations.AlterModelOptions(
            name='pokerevent',
            options={'get_latest_by': 'updated_at', 'ordering': ['event_date']},
        ),
        migrations.AlterField(
            model_name='gamescore',
            name='score',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='monthlygame',
            name='month',
            field=models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='monthlygame',
            name='uploaded_file',
            field=models.FileField(upload_to='monthly_games/'),
        ),
        migrations.AlterField(
            model_name='overallstats',
            name='uploaded_file',
            field=models.FileField(upload_to='overall_stats/'),
        ),
        migrations.AlterField(
            model_name='overallstats',
            name='year',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='playeroverallstat',
            name='eoy_pool',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pokerevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='pokerevent',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='pokerevent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
