# Generated by Django 5.1.5 on 2026-04-04 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvapp', '0004_announcement_highhand'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokerevent',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
