# Generated by Django 5.1.5 on 2026-04-07 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvapp', '0007_sitesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['email'],
            },
        ),
    ]
