# Generated by Django 5.1.5 on 2026-04-22 20:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvapp', '0009_pushtoken'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_internal_tester', models.BooleanField(default=False, help_text='Receives push notifications sent to the internal-tester audience.')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EventPushLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('headcount_nudge', 'Headcount Nudge'), ('day_of', 'Day-of Reminder')], max_length=20)),
                ('sent_date', models.DateField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_logs', to='csvapp.pokerevent')),
            ],
            options={
                'unique_together': {('event', 'kind', 'sent_date')},
            },
        ),
    ]
