# Generated by Django 5.1.5 on 2026-04-22 20:22

from django.conf import settings
from django.db import migrations


def create_missing_profiles(apps, schema_editor):
    User = apps.get_model(settings.AUTH_USER_MODEL)
    UserProfile = apps.get_model('csvapp', 'UserProfile')
    existing = set(UserProfile.objects.values_list('user_id', flat=True))
    UserProfile.objects.bulk_create([
        UserProfile(user=user, is_internal_tester=False)
        for user in User.objects.exclude(pk__in=existing)
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('csvapp', '0010_userprofile_eventpushlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(create_missing_profiles, migrations.RunPython.noop),
    ]
